spring:
  application:
   name: retirement-planner
   version: 1.0.0
  output: 
    ansi:
      enabled: always
  # Store all sensitive information within .env
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  
  # used to pass .env values to .yml file
  config:
    import: optional:file:.env[.properties]

# JWT settings (secret-key must be a Base64-encoded value; keep it in .env)
security:
  jwt:
    secret-key: ${JWT_SECRET_KEY}
    expiration-time: 3600000

# may use different ports so store in .env
server:
  port: ${PORT}

