INSERT INTO goal (user_id, name, target_retirement_age, target_amount, notes) VALUES
    (1, 'Early Retirement Core Plan', 58, 1200000.00, 'Primary goal targeting an early exit from full-time work.'),
    (1, 'Standard Retirement Plan', 67, 950000.00, 'Traditional long-term retirement target at full retirement age.'),
    (1, 'Healthcare Reserve Fund', 65, 250000.00, 'Reserve to cover pre-Medicare and supplemental healthcare costs.'),
    (1, 'Travel & Leisure Fund', 62, 150000.00, 'Discretionary fund for post-retirement travel.'),
    (1, 'Legacy & Inheritance Goal', 70, 500000.00, 'Long-horizon goal to leave an inheritance.'),
    (1, 'Home Downsizing Buffer', 60, 300000.00, 'Buffer to smooth the transition when downsizing the family home.'),
    (1, 'Long-Term Care Reserve', 68, 400000.00, 'Reserve earmarked for potential long-term care needs.'),
    (1, 'Part-Time Transition Goal', 55, 600000.00, 'Funds a gradual transition into part-time work before full retirement.'),
    (1, 'Emergency Retirement Cushion', 63, 200000.00, 'Cushion against market downturns near the retirement date.'),
    (1, 'Roth Conversion Ladder Goal', 59, 350000.00, 'Supports a multi-year Roth conversion ladder strategy.'),
    (1, 'Grandchildren Education Gift', 66, 100000.00, 'Set aside for future education gifts to grandchildren.'),
    (1, 'Second Home Fund', 61, 450000.00, 'Goal for purchasing a second/vacation home.'),
    (1, 'Charitable Giving Reserve', 69, 275000.00, 'Reserve for planned charitable giving in retirement.'),
    (1, 'Social Security Bridge Fund', 64, 180000.00, 'Bridges income between retirement and claiming Social Security.'),
    (1, 'Catch-Up Contribution Goal', 57, 325000.00, 'Aggressive catch-up savings goal in the final working years.'),
    (2, 'Early Retirement Core Plan', 58, 1200000.00, 'Primary goal targeting an early exit from full-time work.'),
    (2, 'Standard Retirement Plan', 67, 950000.00, 'Traditional long-term retirement target at full retirement age.'),
    (2, 'Healthcare Reserve Fund', 65, 250000.00, 'Reserve to cover pre-Medicare and supplemental healthcare costs.'),
    (2, 'Travel & Leisure Fund', 62, 150000.00, 'Discretionary fund for post-retirement travel.'),
    (2, 'Legacy & Inheritance Goal', 70, 500000.00, 'Long-horizon goal to leave an inheritance.'),
    (2, 'Home Downsizing Buffer', 60, 300000.00, 'Buffer to smooth the transition when downsizing the family home.'),
    (2, 'Long-Term Care Reserve', 68, 400000.00, 'Reserve earmarked for potential long-term care needs.'),
    (2, 'Part-Time Transition Goal', 55, 600000.00, 'Funds a gradual transition into part-time work before full retirement.'),
    (2, 'Emergency Retirement Cushion', 63, 200000.00, 'Cushion against market downturns near the retirement date.'),
    (2, 'Roth Conversion Ladder Goal', 59, 350000.00, 'Supports a multi-year Roth conversion ladder strategy.'),
    (2, 'Grandchildren Education Gift', 66, 100000.00, 'Set aside for future education gifts to grandchildren.'),
    (2, 'Second Home Fund', 61, 450000.00, 'Goal for purchasing a second/vacation home.'),
    (2, 'Charitable Giving Reserve', 69, 275000.00, 'Reserve for planned charitable giving in retirement.'),
    (2, 'Social Security Bridge Fund', 64, 180000.00, 'Bridges income between retirement and claiming Social Security.'),
    (2, 'Catch-Up Contribution Goal', 57, 325000.00, 'Aggressive catch-up savings goal in the final working years.'),
    (3, 'Early Retirement Core Plan', 58, 1200000.00, 'Primary goal targeting an early exit from full-time work.'),
    (3, 'Standard Retirement Plan', 67, 950000.00, 'Traditional long-term retirement target at full retirement age.'),
    (3, 'Healthcare Reserve Fund', 65, 250000.00, 'Reserve to cover pre-Medicare and supplemental healthcare costs.'),
    (3, 'Travel & Leisure Fund', 62, 150000.00, 'Discretionary fund for post-retirement travel.'),
    (3, 'Legacy & Inheritance Goal', 70, 500000.00, 'Long-horizon goal to leave an inheritance.'),
    (3, 'Home Downsizing Buffer', 60, 300000.00, 'Buffer to smooth the transition when downsizing the family home.'),
    (3, 'Long-Term Care Reserve', 68, 400000.00, 'Reserve earmarked for potential long-term care needs.'),
    (3, 'Part-Time Transition Goal', 55, 600000.00, 'Funds a gradual transition into part-time work before full retirement.'),
    (3, 'Emergency Retirement Cushion', 63, 200000.00, 'Cushion against market downturns near the retirement date.'),
    (3, 'Roth Conversion Ladder Goal', 59, 350000.00, 'Supports a multi-year Roth conversion ladder strategy.'),
    (3, 'Grandchildren Education Gift', 66, 100000.00, 'Set aside for future education gifts to grandchildren.'),
    (3, 'Second Home Fund', 61, 450000.00, 'Goal for purchasing a second/vacation home.'),
    (3, 'Charitable Giving Reserve', 69, 275000.00, 'Reserve for planned charitable giving in retirement.'),
    (3, 'Social Security Bridge Fund', 64, 180000.00, 'Bridges income between retirement and claiming Social Security.'),
    (3, 'Catch-Up Contribution Goal', 57, 325000.00, 'Aggressive catch-up savings goal in the final working years.'),
    (4, 'Early Retirement Core Plan', 58, 1200000.00, 'Primary goal targeting an early exit from full-time work.'),
    (4, 'Standard Retirement Plan', 67, 950000.00, 'Traditional long-term retirement target at full retirement age.'),
    (4, 'Healthcare Reserve Fund', 65, 250000.00, 'Reserve to cover pre-Medicare and supplemental healthcare costs.'),
    (4, 'Travel & Leisure Fund', 62, 150000.00, 'Discretionary fund for post-retirement travel.'),
    (4, 'Legacy & Inheritance Goal', 70, 500000.00, 'Long-horizon goal to leave an inheritance.'),
    (4, 'Home Downsizing Buffer', 60, 300000.00, 'Buffer to smooth the transition when downsizing the family home.'),
    (4, 'Long-Term Care Reserve', 68, 400000.00, 'Reserve earmarked for potential long-term care needs.'),
    (4, 'Part-Time Transition Goal', 55, 600000.00, 'Funds a gradual transition into part-time work before full retirement.'),
    (4, 'Emergency Retirement Cushion', 63, 200000.00, 'Cushion against market downturns near the retirement date.'),
    (4, 'Roth Conversion Ladder Goal', 59, 350000.00, 'Supports a multi-year Roth conversion ladder strategy.'),
    (4, 'Grandchildren Education Gift', 66, 100000.00, 'Set aside for future education gifts to grandchildren.'),
    (4, 'Second Home Fund', 61, 450000.00, 'Goal for purchasing a second/vacation home.'),
    (4, 'Charitable Giving Reserve', 69, 275000.00, 'Reserve for planned charitable giving in retirement.'),
    (4, 'Social Security Bridge Fund', 64, 180000.00, 'Bridges income between retirement and claiming Social Security.'),
    (4, 'Catch-Up Contribution Goal', 57, 325000.00, 'Aggressive catch-up savings goal in the final working years.');

INSERT INTO funding_source (user_id, name, source_type, institution, notes) VALUES
    (1, 'Fidelity Traditional 401(k)', 'TRADITIONAL_401K', 'Fidelity', 'My Demo Funded Source detailed notes'),
    (1, 'Vanguard Roth 401(k)', 'ROTH_401K', 'Vanguard', 'My Demo Funded Source detailed notes'),
    (1, 'Charles Schwab Traditional IRA', 'TRADITIONAL_IRA', 'Charles Schwab', 'My Demo Funded Source detailed notes'),
    (1, 'T. Rowe Price Roth IRA', 'ROTH_IRA', 'T. Rowe Price', 'My Demo Funded Source detailed notes'),
    (1, 'Empower SEP IRA', 'SEP_IRA', 'Empower', 'My Demo Funded Source detailed notes'),
    (1, 'Merrill Lynch Taxable Brokerage', 'TAXABLE_BROKERAGE', 'Merrill Lynch', 'My Demo Funded Source detailed notes'),
    (1, 'E*TRADE Traditional 401(k)', 'TRADITIONAL_401K', 'E*TRADE', 'My Demo Funded Source detailed notes'),
    (1, 'Betterment Roth 401(k)', 'ROTH_401K', 'Betterment', 'My Demo Funded Source detailed notes'),
    (1, 'Fidelity Traditional IRA', 'TRADITIONAL_IRA', 'Fidelity', 'My Demo Funded Source detailed notes'),
    (1, 'Vanguard Roth IRA', 'ROTH_IRA', 'Vanguard', 'My Demo Funded Source detailed notes'),
    (1, 'Charles Schwab SEP IRA', 'SEP_IRA', 'Charles Schwab', 'My Demo Funded Source detailed notes'),
    (1, 'T. Rowe Price Taxable Brokerage', 'TAXABLE_BROKERAGE', 'T. Rowe Price', 'My Demo Funded Source detailed notes'),
    (1, 'Empower Traditional 401(k)', 'TRADITIONAL_401K', 'Empower', 'My Demo Funded Source detailed notes'),
    (1, 'Merrill Lynch Roth 401(k)', 'ROTH_401K', 'Merrill Lynch', 'My Demo Funded Source detailed notes'),
    (1, 'E*TRADE Traditional IRA', 'TRADITIONAL_IRA', 'E*TRADE', 'My Demo Funded Source detailed notes'),
    (2, 'Vanguard Traditional 401(k)', 'TRADITIONAL_401K', 'Vanguard', 'My Demo Funded Source detailed notes'),
    (2, 'Charles Schwab Roth 401(k)', 'ROTH_401K', 'Charles Schwab', 'My Demo Funded Source detailed notes'),
    (2, 'T. Rowe Price Traditional IRA', 'TRADITIONAL_IRA', 'T. Rowe Price', 'My Demo Funded Source detailed notes'),
    (2, 'Empower Roth IRA', 'ROTH_IRA', 'Empower', 'My Demo Funded Source detailed notes'),
    (2, 'Merrill Lynch SEP IRA', 'SEP_IRA', 'Merrill Lynch', 'My Demo Funded Source detailed notes'),
    (2, 'E*TRADE Taxable Brokerage', 'TAXABLE_BROKERAGE', 'E*TRADE', 'My Demo Funded Source detailed notes'),
    (2, 'Betterment Traditional 401(k)', 'TRADITIONAL_401K', 'Betterment', 'My Demo Funded Source detailed notes'),
    (2, 'Fidelity Roth 401(k)', 'ROTH_401K', 'Fidelity', 'My Demo Funded Source detailed notes'),
    (2, 'Vanguard Traditional IRA', 'TRADITIONAL_IRA', 'Vanguard', 'My Demo Funded Source detailed notes'),
    (2, 'Charles Schwab Roth IRA', 'ROTH_IRA', 'Charles Schwab', 'My Demo Funded Source detailed notes'),
    (2, 'T. Rowe Price SEP IRA', 'SEP_IRA', 'T. Rowe Price', 'My Demo Funded Source detailed notes'),
    (2, 'Empower Taxable Brokerage', 'TAXABLE_BROKERAGE', 'Empower', 'My Demo Funded Source detailed notes'),
    (2, 'Merrill Lynch Traditional 401(k)', 'TRADITIONAL_401K', 'Merrill Lynch', 'My Demo Funded Source detailed notes'),
    (2, 'E*TRADE Roth 401(k)', 'ROTH_401K', 'E*TRADE', 'My Demo Funded Source detailed notes'),
    (2, 'Betterment Traditional IRA', 'TRADITIONAL_IRA', 'Betterment', 'My Demo Funded Source detailed notes'),
    (3, 'Charles Schwab Traditional 401(k)', 'TRADITIONAL_401K', 'Charles Schwab', 'My Demo Funded Source detailed notes'),
    (3, 'T. Rowe Price Roth 401(k)', 'ROTH_401K', 'T. Rowe Price', 'My Demo Funded Source detailed notes'),
    (3, 'Empower Traditional IRA', 'TRADITIONAL_IRA', 'Empower', 'My Demo Funded Source detailed notes'),
    (3, 'Merrill Lynch Roth IRA', 'ROTH_IRA', 'Merrill Lynch', 'My Demo Funded Source detailed notes'),
    (3, 'E*TRADE SEP IRA', 'SEP_IRA', 'E*TRADE', 'My Demo Funded Source detailed notes'),
    (3, 'Betterment Taxable Brokerage', 'TAXABLE_BROKERAGE', 'Betterment', 'My Demo Funded Source detailed notes'),
    (3, 'Fidelity Traditional 401(k)', 'TRADITIONAL_401K', 'Fidelity', 'My Demo Funded Source detailed notes'),
    (3, 'Vanguard Roth 401(k)', 'ROTH_401K', 'Vanguard', 'My Demo Funded Source detailed notes'),
    (3, 'Charles Schwab Traditional IRA', 'TRADITIONAL_IRA', 'Charles Schwab', 'My Demo Funded Source detailed notes'),
    (3, 'T. Rowe Price Roth IRA0', 'ROTH_IRA', 'T. Rowe Price', 'My Demo Funded Source detailed notes'),
    (3, 'Empower SEP IRA1', 'SEP_IRA', 'Empower', 'My Demo Funded Source detailed notes'),
    (3, 'Merrill Lynch Taxable Brokerage', 'TAXABLE_BROKERAGE', 'Merrill Lynch', 'My Demo Funded Source detailed notes'),
    (3, 'E*TRADE Traditional 401(k)', 'TRADITIONAL_401K', 'E*TRADE', 'My Demo Funded Source detailed notes'),
    (3, 'Betterment Roth 401(k)', 'ROTH_401K', 'Betterment', 'My Demo Funded Source detailed notes'),
    (3, 'Fidelity Traditional IRA', 'TRADITIONAL_IRA', 'Fidelity', 'My Demo Funded Source detailed notes'),
    (4, 'T. Rowe Price Traditional 401(k)', 'TRADITIONAL_401K', 'T. Rowe Price', 'My Demo Funded Source detailed notes'),
    (4, 'Empower Roth 401(k)', 'ROTH_401K', 'Empower', 'My Demo Funded Source detailed notes'),
    (4, 'Merrill Lynch Traditional IRA', 'TRADITIONAL_IRA', 'Merrill Lynch', 'My Demo Funded Source detailed notes'),
    (4, 'E*TRADE Roth IRA', 'ROTH_IRA', 'E*TRADE', 'My Demo Funded Source detailed notes'),
    (4, 'Betterment SEP IRA', 'SEP_IRA', 'Betterment', 'My Demo Funded Source detailed notes'),
    (4, 'Fidelity Taxable Brokerage', 'TAXABLE_BROKERAGE', 'Fidelity', 'My Demo Funded Source detailed notes'),
    (4, 'Vanguard Traditional 401(k)', 'TRADITIONAL_401K', 'Vanguard', 'My Demo Funded Source detailed notes'),
    (4, 'Charles Schwab Roth 401(k)', 'ROTH_401K', 'Charles Schwab', 'My Demo Funded Source detailed notes'),
    (4, 'T. Rowe Price Traditional IRA', 'TRADITIONAL_IRA', 'T. Rowe Price', 'My Demo Funded Source detailed notes'),
    (4, 'Empower Roth IRA0', 'ROTH_IRA', 'Empower', 'My Demo Funded Source detailed notes'),
    (4, 'Merrill Lynch SEP IRA1', 'SEP_IRA', 'Merrill Lynch', 'My Demo Funded Source detailed notes'),
    (4, 'E*TRADE Taxable Brokerage', 'TAXABLE_BROKERAGE', 'E*TRADE', 'My Demo Funded Source detailed notes'),
    (4, 'Betterment Traditional 401(k)', 'TRADITIONAL_401K', 'Betterment', 'My Demo Funded Source detailed notes'),
    (4, 'Fidelity Roth 401(k)', 'ROTH_401K', 'Fidelity', 'My Demo Funded Source detailed notes'),
    (4, 'Vanguard Traditional IRA', 'TRADITIONAL_IRA', 'Vanguard', 'My Demo Funded Source detailed notes');

INSERT INTO contribution_record (user_id, goal_id, funding_source_id, amount, contribution_date, category, notes) VALUES
    (1, 1, 1, 150.00, '2025-08-15', 'EMPLOYEE_SALARY_DEFERRAL', 'My Demo Contribution to show values in the database.'),
    (1, 2, 4, 187.50, '2025-09-15', 'EMPLOYER_MATCH', 'My Demo Contribution to show values in the database.'),
    (1, 3, 7, 225.00, '2025-10-15', 'CATCH_UP_CONTRIBUTION', 'My Demo Contribution to show values in the database.'),
    (1, 4, 10, 262.50, '2025-11-15', 'ROLLOVER', 'My Demo Contribution to show values in the database.'),
    (1, 5, 13, 300.00, '2025-12-15', 'EMPLOYEE_SALARY_DEFERRAL', 'My Demo Contribution to show values in the database.'),
    (1, 6, 1, 337.50, '2026-01-15', 'EMPLOYER_MATCH', 'My Demo Contribution to show values in the database.'),
    (1, 7, 4, 375.00, '2026-02-15', 'CATCH_UP_CONTRIBUTION', 'My Demo Contribution to show values in the database.'),
    (1, 8, 7, 412.50, '2026-03-15', 'ROLLOVER', 'My Demo Contribution to show values in the database.'),
    (1, 9, 10, 450.00, '2026-04-15', 'EMPLOYEE_SALARY_DEFERRAL', 'My Demo Contribution to show values in the database.'),
    (1, 10, 13, 487.50, '2026-05-15', 'EMPLOYER_MATCH', 'My Demo Contribution to show values in the database.'),
    (1, 11, 1, 525.00, '2026-06-15', 'CATCH_UP_CONTRIBUTION', 'My Demo Contribution to show values in the database.'),
    (1, 12, 4, 562.50, '2026-07-15', 'ROLLOVER', 'My Demo Contribution to show values in the database.'),
    (2, 16, 17, 175.00, '2025-08-15', 'EMPLOYEE_SALARY_DEFERRAL', 'My Demo Contribution to show values in the database.'),
    (2, 17, 20, 212.50, '2025-09-15', 'EMPLOYER_MATCH', 'My Demo Contribution to show values in the database.'),
    (2, 18, 23, 250.00, '2025-10-15', 'CATCH_UP_CONTRIBUTION', 'My Demo Contribution to show values in the database.'),
    (2, 19, 26, 287.50, '2025-11-15', 'ROLLOVER', 'My Demo Contribution to show values in the database.'),
    (2, 20, 29, 325.00, '2025-12-15', 'EMPLOYEE_SALARY_DEFERRAL', 'My Demo Contribution to show values in the database.'),
    (2, 21, 17, 362.50, '2026-01-15', 'EMPLOYER_MATCH', 'My Demo Contribution to show values in the database.'),
    (2, 22, 20, 400.00, '2026-02-15', 'CATCH_UP_CONTRIBUTION', 'My Demo Contribution to show values in the database.'),
    (2, 23, 23, 437.50, '2026-03-15', 'ROLLOVER', 'My Demo Contribution to show values in the database.'),
    (2, 24, 26, 475.00, '2026-04-15', 'EMPLOYEE_SALARY_DEFERRAL', 'My Demo Contribution to show values in the database.'),
    (2, 25, 29, 512.50, '2026-05-15', 'EMPLOYER_MATCH', 'My Demo Contribution to show values in the database.'),
    (2, 26, 17, 550.00, '2026-06-15', 'CATCH_UP_CONTRIBUTION', 'My Demo Contribution to show values in the database.'),
    (2, 27, 20, 587.50, '2026-07-15', 'ROLLOVER', 'My Demo Contribution to show values in the database.'),
    (3, 31, 33, 200.00, '2025-08-15', 'EMPLOYEE_SALARY_DEFERRAL', 'My Demo Contribution to show values in the database.'),
    (3, 32, 36, 237.50, '2025-09-15', 'EMPLOYER_MATCH', 'My Demo Contribution to show values in the database.'),
    (3, 33, 39, 275.00, '2025-10-15', 'CATCH_UP_CONTRIBUTION', 'My Demo Contribution to show values in the database.'),
    (3, 34, 42, 312.50, '2025-11-15', 'ROLLOVER', 'My Demo Contribution to show values in the database.'),
    (3, 35, 45, 350.00, '2025-12-15', 'EMPLOYEE_SALARY_DEFERRAL', 'My Demo Contribution to show values in the database.'),
    (3, 36, 33, 387.50, '2026-01-15', 'EMPLOYER_MATCH', 'My Demo Contribution to show values in the database.'),
    (3, 37, 36, 425.00, '2026-02-15', 'CATCH_UP_CONTRIBUTION', 'My Demo Contribution to show values in the database.'),
    (3, 38, 39, 462.50, '2026-03-15', 'ROLLOVER', 'My Demo Contribution to show values in the database.'),
    (3, 39, 42, 500.00, '2026-04-15', 'EMPLOYEE_SALARY_DEFERRAL', 'My Demo Contribution to show values in the database.'),
    (3, 40, 45, 537.50, '2026-05-15', 'EMPLOYER_MATCH', 'My Demo Contribution to show values in the database.'),
    (3, 41, 33, 575.00, '2026-06-15', 'CATCH_UP_CONTRIBUTION', 'My Demo Contribution to show values in the database.'),
    (3, 42, 36, 612.50, '2026-07-15', 'ROLLOVER', 'My Demo Contribution to show values in the database.'),
    (4, 46, 49, 225.00, '2025-08-15', 'EMPLOYEE_SALARY_DEFERRAL', 'My Demo Contribution to show values in the database.'),
    (4, 47, 52, 262.50, '2025-09-15', 'EMPLOYER_MATCH', 'My Demo Contribution to show values in the database.'),
    (4, 48, 55, 300.00, '2025-10-15', 'CATCH_UP_CONTRIBUTION', 'My Demo Contribution to show values in the database.'),
    (4, 49, 58, 337.50, '2025-11-15', 'ROLLOVER', 'My Demo Contribution to show values in the database.'),
    (4, 50, 46, 375.00, '2025-12-15', 'EMPLOYEE_SALARY_DEFERRAL', 'My Demo Contribution to show values in the database.'),
    (4, 51, 49, 412.50, '2026-01-15', 'EMPLOYER_MATCH', 'My Demo Contribution to show values in the database.'),
    (4, 52, 52, 450.00, '2026-02-15', 'CATCH_UP_CONTRIBUTION', 'My Demo Contribution to show values in the database.'),
    (4, 53, 55, 487.50, '2026-03-15', 'ROLLOVER', 'My Demo Contribution to show values in the database.'),
    (4, 54, 58, 525.00, '2026-04-15', 'EMPLOYEE_SALARY_DEFERRAL', 'My Demo Contribution to show values in the database.'),
    (4, 55, 46, 562.50, '2026-05-15', 'EMPLOYER_MATCH', 'My Demo Contribution to show values in the database.'),
    (4, 56, 49, 600.00, '2026-06-15', 'CATCH_UP_CONTRIBUTION', 'My Demo Contribution to show values in the database.'),
    (4, 57, 52, 637.50, '2026-07-15', 'ROLLOVER', 'My Demo Contribution to show values in the database.');
